baseURL = "https://capibaragames.com"
languageCode = "es-mx"
title = "CAPIBARA GAMES DevBlog"
theme = "PaperMod"

# Paginación
[pagination]
  pagerSize = 5

# ---------------------------
# CONFIGURACIÓN DE PAPERMOD
# ---------------------------
[params]
  defaultTheme = "auto"
  showToc = true

  # --- HOME INFO MODE ---
  [params.homeInfoParams]
    Title = "Hola, soy CAPIBARA GAMES"
    Content = """Aquí documentamos nuestro viaje de desarrollo de videojuegos.  
    Explora nuestros últimos [Posts](/posts/) y [Juegos](/juegos/)."""

  # --- ARCHIVO Y BUSCADOR ---
  showArchive = true
  showSearch = true

  # Configuración del buscador
  [params.search]
    provider = "lunr"    # opciones: "lunr", "algolia", "fuse"
    fuse = { isCaseSensitive = false, shouldSort = true, location = 0, distance = 100, threshold = 0.4 }

  # --- REDES SOCIALES (opcional) ---
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/CAPIBARAGAMES"

  [[params.socialIcons]]
    name = "itchio"
    url = "https://capibaragamesitchio.itch.io/"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@CapibaraGamesDev"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/LuisEnr38013315"
# ---------------------------
# MENÚS DE NAVEGACIÓN
# ---------------------------
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 2
    
  [[menu.main]]
    identifier = "juegos"
    name = "Juegos"
    url = "/juegos/"
    weight = 3
    
  [[menu.main]]
    identifier = "archive"
    name = "Archivo"
    url = "/archives/"
    weight = 4
    
  [[menu.main]]
    identifier = "search"
    name = "Buscar"
    url = "/search/"
    weight = 5
